
import {
  Home,
  Users,
  PlusCircle,
  MoreVertical,
  ChevronDown,
  Trash2,
  Edit,
  MapPin,
  GitCommit,
  X,
  Check,
  Archive,
  AlertTriangle,
  FileText,
  Filter,
  Search,
  ClipboardList,
  Skull,
  FileDown,
} from 'lucide-react';

export const Icons = {
  Cow: Users,
  Calf: GitCommit,
  Plus: PlusCircle,
  More: MoreVertical,
  ChevronDown: ChevronDown,
  Trash: Trash2,
  Edit: Edit,
  Location: MapPin,
  Infirmary: PlusCircle,
  Close: X,
  Check: Check,
  Sales: Archive,
  Warning: AlertTriangle,
  Treatment: FileText,
  Filter: Filter,
  Search: Search,
  Horse: ClipboardList,
  Skull: Skull,
  Export: FileDown,
};
